/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

/**
 *
 * @author PMYLS
 */

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.BorderFactory;

public class CalculatorUi extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorUi
     */
    
    String value;
    double num1, num2, result;
    String operator;
    ArrayList<String> historyResult = new ArrayList<>(); // History store karne ke liye
    public CalculatorUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        canvas1 = new java.awt.Canvas();
        jLabel3 = new javax.swing.JLabel();
        AC = new javax.swing.JToggleButton();
        div = new javax.swing.JToggleButton();
        mul = new javax.swing.JToggleButton();
        sub = new javax.swing.JToggleButton();
        b9 = new javax.swing.JToggleButton();
        b8 = new javax.swing.JToggleButton();
        b7 = new javax.swing.JToggleButton();
        b4 = new javax.swing.JToggleButton();
        b5 = new javax.swing.JToggleButton();
        b6 = new javax.swing.JToggleButton();
        add = new javax.swing.JToggleButton();
        equal = new javax.swing.JToggleButton();
        b3 = new javax.swing.JToggleButton();
        bpoint = new javax.swing.JToggleButton();
        b2 = new javax.swing.JToggleButton();
        b1 = new javax.swing.JToggleButton();
        history = new javax.swing.JToggleButton();
        b0 = new javax.swing.JToggleButton();
        outputResult = new javax.swing.JTextField();
        btnBackspace = new javax.swing.JToggleButton();

        jLabel1.setBackground(new java.awt.Color(24, 168, 197));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(42, 162, 238), 3));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(147, 176, 243), 4));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 450));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Calculator");

        AC.setBackground(new java.awt.Color(121, 124, 124));
        AC.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        AC.setForeground(new java.awt.Color(255, 255, 255));
        AC.setText("AC");
        AC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AC.setMargin(new java.awt.Insets(0, 0, 0, 0));
        AC.setMaximumSize(new java.awt.Dimension(60, 60));
        AC.setMinimumSize(new java.awt.Dimension(60, 60));
        AC.setPreferredSize(new java.awt.Dimension(60, 60));
        AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACActionPerformed(evt);
            }
        });

        div.setBackground(new java.awt.Color(0, 93, 175));
        div.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        div.setForeground(new java.awt.Color(255, 255, 255));
        div.setText("/");
        div.setMaximumSize(new java.awt.Dimension(60, 60));
        div.setMinimumSize(new java.awt.Dimension(60, 60));
        div.setPreferredSize(new java.awt.Dimension(60, 60));
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });

        mul.setBackground(new java.awt.Color(0, 93, 175));
        mul.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        mul.setForeground(new java.awt.Color(255, 255, 255));
        mul.setText("*");
        mul.setMaximumSize(new java.awt.Dimension(60, 60));
        mul.setMinimumSize(new java.awt.Dimension(60, 60));
        mul.setPreferredSize(new java.awt.Dimension(60, 60));
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulActionPerformed(evt);
            }
        });

        sub.setBackground(new java.awt.Color(0, 93, 175));
        sub.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        sub.setForeground(new java.awt.Color(255, 255, 255));
        sub.setText("-");
        sub.setMaximumSize(new java.awt.Dimension(60, 60));
        sub.setMinimumSize(new java.awt.Dimension(60, 60));
        sub.setPreferredSize(new java.awt.Dimension(60, 60));
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(48, 48, 56));
        b9.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        b9.setForeground(new java.awt.Color(0, 146, 211));
        b9.setText("9");
        b9.setMaximumSize(new java.awt.Dimension(60, 60));
        b9.setMinimumSize(new java.awt.Dimension(60, 60));
        b9.setPreferredSize(new java.awt.Dimension(60, 60));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(48, 48, 56));
        b8.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        b8.setForeground(new java.awt.Color(0, 146, 211));
        b8.setText("8");
        b8.setMaximumSize(new java.awt.Dimension(60, 60));
        b8.setMinimumSize(new java.awt.Dimension(60, 60));
        b8.setPreferredSize(new java.awt.Dimension(60, 60));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(48, 48, 56));
        b7.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        b7.setForeground(new java.awt.Color(0, 146, 211));
        b7.setText("7");
        b7.setMaximumSize(new java.awt.Dimension(60, 60));
        b7.setMinimumSize(new java.awt.Dimension(60, 60));
        b7.setPreferredSize(new java.awt.Dimension(60, 60));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(48, 48, 56));
        b4.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        b4.setForeground(new java.awt.Color(0, 146, 211));
        b4.setText("4");
        b4.setMaximumSize(new java.awt.Dimension(60, 60));
        b4.setMinimumSize(new java.awt.Dimension(60, 60));
        b4.setPreferredSize(new java.awt.Dimension(60, 60));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(48, 48, 56));
        b5.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        b5.setForeground(new java.awt.Color(0, 146, 211));
        b5.setText("5");
        b5.setMaximumSize(new java.awt.Dimension(60, 60));
        b5.setMinimumSize(new java.awt.Dimension(60, 60));
        b5.setPreferredSize(new java.awt.Dimension(60, 60));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(48, 48, 56));
        b6.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        b6.setForeground(new java.awt.Color(0, 146, 211));
        b6.setText("6");
        b6.setMaximumSize(new java.awt.Dimension(60, 60));
        b6.setMinimumSize(new java.awt.Dimension(60, 60));
        b6.setPreferredSize(new java.awt.Dimension(60, 60));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        add.setBackground(new java.awt.Color(0, 93, 175));
        add.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("+");
        add.setPreferredSize(new java.awt.Dimension(30, 30));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        equal.setBackground(new java.awt.Color(0, 146, 211));
        equal.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        equal.setForeground(new java.awt.Color(255, 255, 255));
        equal.setText("=");
        equal.setPreferredSize(new java.awt.Dimension(30, 30));
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(48, 48, 56));
        b3.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        b3.setForeground(new java.awt.Color(0, 146, 211));
        b3.setText("3");
        b3.setMaximumSize(new java.awt.Dimension(60, 60));
        b3.setMinimumSize(new java.awt.Dimension(60, 60));
        b3.setPreferredSize(new java.awt.Dimension(60, 60));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        bpoint.setBackground(new java.awt.Color(121, 124, 124));
        bpoint.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        bpoint.setForeground(new java.awt.Color(255, 255, 255));
        bpoint.setText(".");
        bpoint.setMaximumSize(new java.awt.Dimension(60, 60));
        bpoint.setMinimumSize(new java.awt.Dimension(60, 60));
        bpoint.setPreferredSize(new java.awt.Dimension(60, 60));
        bpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpointActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(48, 48, 56));
        b2.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        b2.setForeground(new java.awt.Color(0, 146, 211));
        b2.setText("2");
        b2.setMaximumSize(new java.awt.Dimension(60, 60));
        b2.setMinimumSize(new java.awt.Dimension(60, 60));
        b2.setPreferredSize(new java.awt.Dimension(60, 60));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(48, 48, 56));
        b1.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 146, 211));
        b1.setText("1");
        b1.setMaximumSize(new java.awt.Dimension(60, 60));
        b1.setMinimumSize(new java.awt.Dimension(60, 60));
        b1.setPreferredSize(new java.awt.Dimension(60, 60));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        history.setBackground(new java.awt.Color(6, 57, 112));
        history.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        history.setForeground(new java.awt.Color(255, 255, 255));
        history.setText("H");
        history.setMaximumSize(new java.awt.Dimension(60, 60));
        history.setMinimumSize(new java.awt.Dimension(60, 60));
        history.setPreferredSize(new java.awt.Dimension(60, 60));
        history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyActionPerformed(evt);
            }
        });

        b0.setBackground(new java.awt.Color(48, 48, 56));
        b0.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        b0.setForeground(new java.awt.Color(0, 146, 211));
        b0.setText("0");
        b0.setMaximumSize(new java.awt.Dimension(60, 60));
        b0.setMinimumSize(new java.awt.Dimension(60, 60));
        b0.setPreferredSize(new java.awt.Dimension(60, 60));
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        outputResult.setBackground(new java.awt.Color(0, 0, 0));
        outputResult.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        outputResult.setForeground(new java.awt.Color(255, 255, 255));
        outputResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        outputResult.setBorder(null);
        outputResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputResultActionPerformed(evt);
            }
        });

        btnBackspace.setBackground(new java.awt.Color(121, 124, 124));
        btnBackspace.setFont(new java.awt.Font("Myanmar Text", 1, 16)); // NOI18N
        btnBackspace.setForeground(new java.awt.Color(255, 255, 255));
        btnBackspace.setText("<-");
        btnBackspace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBackspace.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnBackspace.setMaximumSize(new java.awt.Dimension(60, 60));
        btnBackspace.setMinimumSize(new java.awt.Dimension(60, 60));
        btnBackspace.setPreferredSize(new java.awt.Dimension(60, 60));
        btnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackspaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(history, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(outputResult, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(outputResult, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(history, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackspaceActionPerformed
        JButton btnBackspace = new JButton("<html>&#9003; Backspace</html>"); // &#9003; is Unicode for ⌫

        String text = outputResult.getText(); // TextArea ka text lo
        if (!text.isEmpty()) {
            outputResult.setText(text.substring(0, text.length() - 1)); // Akhri character remove karo
        }
    }//GEN-LAST:event_btnBackspaceActionPerformed

    private void outputResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputResultActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        value = outputResult.getText()+0;
        outputResult.setText(value);
    }//GEN-LAST:event_b0ActionPerformed

    private void historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyActionPerformed
        if (historyResult.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No history available!", "Calculation History", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            // **Pura history text show karega**
            String historyText = String.join("\n", historyResult);
            javax.swing.JOptionPane.showMessageDialog(this, historyText, "Calculation History", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_historyActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        value = outputResult.getText()+1;
        outputResult.setText(value);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        value = outputResult.getText()+2;
        outputResult.setText(value);
    }//GEN-LAST:event_b2ActionPerformed

    private void bpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpointActionPerformed
        value = outputResult.getText()+".";
        outputResult.setText(value);
    }//GEN-LAST:event_bpointActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        value = outputResult.getText()+3;
        outputResult.setText(value);
    }//GEN-LAST:event_b3ActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        String expression = outputResult.getText(); // User ka input expression lo
        try {
            double result = outputResult(expression); // Expression evaluate karo

            // **Formatted result (2 decimal places)**
            String formattedResult = String.format("%.2f", result);

            // **History store karo**
            historyResult.add(expression + " = " + formattedResult);

            // **Previous result delete na ho, next line me dikhaye**
            outputResult.setText(outputResult.getText() + "\n  = " + formattedResult);
        } catch (Exception e) {
            outputResult.setText("Error"); // Agar koi error ho to "Error" show ho
        }
    }//GEN-LAST:event_equalActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        value = outputResult.getText()+" + ";
        outputResult.setText(value);
    }//GEN-LAST:event_addActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        value = outputResult.getText()+6;
        outputResult.setText(value);
    }//GEN-LAST:event_b6ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        value = outputResult.getText()+5;
        outputResult.setText(value);
    }//GEN-LAST:event_b5ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        value = outputResult.getText()+4;
        outputResult.setText(value);
    }//GEN-LAST:event_b4ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        value = outputResult.getText()+7;
        outputResult.setText(value);
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        value = outputResult.getText()+8;
        outputResult.setText(value);
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        value = outputResult.getText()+9;
        outputResult.setText(value);
    }//GEN-LAST:event_b9ActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        value = outputResult.getText()+" - ";
        outputResult.setText(value);
    }//GEN-LAST:event_subActionPerformed

    private void mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulActionPerformed
        value = outputResult.getText()+" * ";
        outputResult.setText(value);
    }//GEN-LAST:event_mulActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        value = outputResult.getText()+" / ";
        outputResult.setText(value);
    }//GEN-LAST:event_divActionPerformed

    private void ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACActionPerformed
        outputResult.setText("");
    }//GEN-LAST:event_ACActionPerformed

    //        ab yahan expression ko nikalna hai user ka input mtlb 
    private double outputResult(String res) {
        ArrayList<Double> numbers = new ArrayList<>();
        ArrayList<Character> operators = new ArrayList<>();

        String num = "";

        // **Step 1: Expression ko numbers & operators me split karo**
        for (int i = 0; i < res.length(); i++) {
            char ch = res.charAt(i);

            if (Character.isDigit(ch) || ch == '.') {
                num += ch; // **Number collect karo**
            } else if (ch == ' ' && !num.isEmpty()) {
                continue; // **Spaces ko ignore karo**
            } else {
                if (!num.isEmpty()) { 
                    numbers.add(Double.parseDouble(num)); // **Number list me add karo**
                    num = ""; // **num ko reset karo**
                }
                operators.add(ch); // **Operator list me add karo**
            }
        }

        // **Agar last me koi number bacha ho, to add karo**
        if (!num.isEmpty()) {
            numbers.add(Double.parseDouble(num));
        }

        // **Step 2: Multiplication & Division ko process karo (BODMAS Rule)**
        for (int i = 0; i < operators.size(); i++) {
            if (operators.get(i) == '*' || operators.get(i) == '/') {
                num1 = numbers.get(i);
                num2 = numbers.get(i + 1);
                result = (operators.get(i) == '*') ? num1 * num2 : num1 / num2;

                numbers.set(i, result); // **Multiplication/Division ka result replace karo**
                numbers.remove(i + 1); // **Next number delete karo**
                operators.remove(i); // **Operator delete karo**
                i--; // **Loop ko adjust karo**
            }
        }

        // **Step 3: Addition & Subtraction ko process karo**
        result = numbers.get(0);
        for (int i = 0; i < operators.size(); i++) {
            if (operators.get(i) == '+') {
                result += numbers.get(i + 1);
            } else if (operators.get(i) == '-') {
                result -= numbers.get(i + 1);
            }
        }

        return result;
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AC;
    private javax.swing.JToggleButton add;
    private javax.swing.JToggleButton b0;
    private javax.swing.JToggleButton b1;
    private javax.swing.JToggleButton b2;
    private javax.swing.JToggleButton b3;
    private javax.swing.JToggleButton b4;
    private javax.swing.JToggleButton b5;
    private javax.swing.JToggleButton b6;
    private javax.swing.JToggleButton b7;
    private javax.swing.JToggleButton b8;
    private javax.swing.JToggleButton b9;
    private javax.swing.JToggleButton bpoint;
    private javax.swing.JToggleButton btnBackspace;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private java.awt.Canvas canvas1;
    private javax.swing.JToggleButton div;
    private javax.swing.JToggleButton equal;
    private javax.swing.JToggleButton history;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JToggleButton mul;
    private javax.swing.JTextField outputResult;
    private javax.swing.JToggleButton sub;
    // End of variables declaration//GEN-END:variables
}
